# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches: [ feature/test ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - run: npm ci
    - run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}
    
    permissions:
      pages: write
      id-token: write
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Install Dependencies
      run: npm ci  # Install dependencies

    - name: Build Project
      run: npm run build  # Run the build script defined in package.json

    - name: Replace Configuration
      run: |
        if [ -z "${{ secrets.USER_NAME }}" ]; then
          echo "Warning: USER_NAME secret is empty"
        fi
        sed -i 's/#{GITHUB_NAME}#/${{ secrets.USER_NAME }}/g' dist/js/config.js
        sed -i 's/#{GITHUB_TITLE}#/${{ secrets.TITLE }}/g' dist/js/config.js
        sed -i 's/#{GITHUB_BIO}#/${{ secrets.BIO }}/g' dist/js/config.js
        sed -i 's/#{GITHUB_LOCATION}#/${{ secrets.LOCATION }}/g' dist/js/config.js
        sed -i 's/#{GITHUB_EMAIL}#/${{ secrets.EMAIL }}/g' dist/js/config.js
        sed -i 's/#{GITHUB_IMAGE}#/${{ secrets.IMAGE }}/g' dist/js/config.js
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.' 
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
